name: blake_hash
description: Provide Blake encryption support, dart implementation library
version: 1.0.2
homepage: https://github.com/litaoh/blake-hash
repository: https://github.com/litaoh/blake-hash
issue_tracker: https://github.com/litaoh/blake-hash/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  convert: ^3.0.1
  pedantic: ^1.8.0
  test: ^1.6.0