name: blake_hash
description: Provide Blake encryption support, dart implementation library
version: 1.0.0
homepage: https://github.com/litaoh/blake-hash

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  hex: ^0.1.2
  pedantic: ^1.8.0
  test: ^1.6.0
